[package]
name = "hello_rust"
version = "0.1.0"
authors = ["ProYi"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
num = "0.4.0"

[[bin]]
name = "new_test"
path = "src/new_test.rs"